### ISSUE TITLE
Plugin keys and tasks for basic functionality

### ISSUE THREAD

**Issue by jdesiloniz** [47deg/sbt-hood#12]
We need to implement the actual settings keys and tasks for the plugin to start building the basic functionality of sbt-hood (i.e.: loading JMH source files, perform comparisons, and return results through the console/GitHub comment - no support for GitHub statuses on our first iteration). Based on the original `hood` plugin I've thought of the following ones:

Settings:

* `previousBenchmarkPath`: File with previous or master benchmark location. By default: master.csv.
* `currentBenchmarkPath`: List of files with current or pull request benchmark location. By default is an empty list.
* `keyColumnName`: Column name to distinguish each benchmark on the comparison. By default: `Benchmark`.
* `compareColumnName`: Column name of the column to compare (values must be 
`Double`). By default: `Score`.
* `thresholdColumnName`: Column name to get the threshold per benchmark. By default: `Score Error (99.9%)`.
* `generalThreshold`: Common threshold to all benchmarks overriding the value coming from thresholdColumnName. Optional.
* `benchmarkThreshold`: Map with a custom threshold per benchmark key overriding the value coming from `thresholdColumnName` or `generalThreshold`. Optional.

* `githubToken`: The Github access token.
* `githubUserId`: id for the user publishing the benchmark comments.
* `repositoryOwner`: The repository owner.
* `repositoryName`: The repository name.
* `pullRequestNumber`: The pull request number.

Tasks:

* `compareBenchmarks`: Compare two benchmarks and print the result.
* `compareBenchmarksCI`: Compare two benchmarks and post/edit a Github comment for a Pull Request (in a later stage this will perform a status update on the PR).

**Comment by AdrianRaFo** [comment]
You don't need the `pullRequestNumber` and the `pullRequestNumber`?
Recently I added `statusTargetUrl` to add a URL on the status directly to the `travis` job

**Comment by jdesiloniz** [comment]
@AdrianRaFo Oops forgot the PR number! For the PR Sha, I was planning to use the PR's `merge_commit_sha` once that field is published by GitHub4s (I added code for that, we just need to release it) so we can always post our statuses there.

@fedefernandez and I discussed on directions to take and we thought that as a first version just posting the benchmark results in the console and/or in a GitHub comment is enough as an MVP. Later we can add status handling with a target url and stuff.

What do you think?
